# Generated by Django 4.1.13 on 2025-04-12 18:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Workflow",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "workflow_type",
                    models.CharField(
                        choices=[
                            ("DATA_PROCESSING", "Traitement de données"),
                            ("SCIENTIFIC_COMPUTING", "Calcul scientifique"),
                            ("RENDERING", "Rendu graphique"),
                            ("MACHINE_LEARNING", "Apprentissage automatique"),
                        ],
                        default="DATA_PROCESSING",
                        max_length=30,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("CREATED", "Créé"),
                            ("VALIDATED", "Validé"),
                            ("SUBMITTED", "Soumis"),
                            ("SPLITTING", "En découpage"),
                            ("ASSIGNING", "En attribution"),
                            ("PENDING", "En attente"),
                            ("RUNNING", "En exécution"),
                            ("PAUSED", "En pause"),
                            ("PARTIAL_FAILURE", "Échec partiel"),
                            ("REASSIGNING", "Réattribution"),
                            ("AGGREGATING", "Agrégation"),
                            ("COMPLETED", "Terminé"),
                            ("FAILED", "Échoué"),
                        ],
                        default="CREATED",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("priority", models.IntegerField(default=1)),
                ("estimated_resources", models.JSONField(default=dict)),
                ("tags", models.JSONField(default=list)),
                ("metadata", models.JSONField(default=dict)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Workflow",
                "verbose_name_plural": "Workflows",
                "ordering": ["-created_at"],
            },
        ),
    ]
