# Generated by Django 4.1.13 on 2025-04-25 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflows", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="workflow",
            name="max_execution_time",
            field=models.IntegerField(default=3600),
        ),
        migrations.AddField(
            model_name="workflow",
            name="max_volunteers",
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name="workflow",
            name="min_volunteers",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="workflow",
            name="retry_count",
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name="workflow",
            name="volunteer_preferences",
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name="workflow",
            name="workflow_type",
            field=models.CharField(
                choices=[
                    ("DATA_PROCESSING", "Traitement de données"),
                    ("SCIENTIFIC_COMPUTING", "Calcul scientifique"),
                    ("RENDERING", "Rendu graphique"),
                    ("MACHINE_LEARNING", "Apprentissage automatique"),
                    ("IMAGE_BATCH_PROCESSING", "Traitement d'images par lot"),
                    ("MODEL_TRAINING", "Entraînement de modèle"),
                ],
                default="DATA_PROCESSING",
                max_length=30,
            ),
        ),
    ]
