# Generated by Django 5.2 on 2025-05-02 13:16

import django.db.models.deletion
import workflows.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "workflows",
            "0002_workflow_max_execution_time_workflow_max_volunteers_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="workflow",
            name="owner",
            field=models.ForeignKey(
                default=workflows.models.get_default_owner,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="workflow",
            name="workflow_type",
            field=models.CharField(
                choices=[
                    ("TEXT_PROCESSING", "Comptage et filtrage de fichiers texte"),
                    ("HASH_CALCULATION", "Calcul de hachage distribué"),
                    ("IMAGE_CONVERSION", "Conversion d'images simple"),
                    ("PDF_GENERATION", "Génération de rapport PDF simple"),
                ],
                default="TEXT_PROCESSING",
                max_length=30,
            ),
        ),
    ]
