# Generated by Django 5.2 on 2025-05-05 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflows", "0003_alter_workflow_owner_alter_workflow_workflow_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workflow",
            name="workflow_type",
            field=models.CharField(
                choices=[
                    ("MATRIX_ADDITION", "Addition de matrices de grande taille"),
                    (
                        "MATRIX_MULTIPLICATION",
                        "Multiplication de matrices de grande taille",
                    ),
                ],
                default="MATRIX_ADDITION",
                max_length=30,
            ),
        ),
    ]
