# Generated by Django 4.2.11 on 2025-06-02 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0002_volunteertask_accepted_at_alter_volunteer_ip_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteertask',
            name='status',
            field=models.CharField(choices=[('ASSIGNED', 'Assigned'), ('ACCEPTED', 'Accepted'), ('STARTED', 'Started'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('EXPIRED', 'Expired'), ('CANCEL', 'Cancel'), ('RUNNING', 'Running'), ('PAUSED', 'Paused')], default='ASSIGNED', max_length=20),
        ),
    ]
