# Generated by Django 4.2.11 on 2025-05-23 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0002_user_remote_id_alter_user_groups_alter_user_is_staff_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflow',
            name='workflow_type',
            field=models.CharField(choices=[('MATRIX_ADDITION', 'Addition de matrices de grande taille'), ('MATRIX_MULTIPLICATION', 'Multiplication de matrices de grande taille'), ('ML_TRAINING', 'Entraînement de modèle machine learning'), ('ML_INFERENCE', 'Inférence de modèle machine learning'), ('CUSTOM', 'Workflow personnalisé')], default='MATRIX_ADDITION', max_length=30),
        ),
    ]
