# Generated by Django 4.1.13 on 2025-04-12 18:52

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("workflows", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("command", models.CharField(max_length=500)),
                ("parameters", models.JSONField(default=list)),
                ("dependencies", models.JSONField(default=list)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "En attente"),
                            ("ASSIGNED", "Assigné"),
                            ("RUNNING", "En exécution"),
                            ("COMPLETED", "Terminé"),
                            ("FAILED", "Échoué"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("is_subtask", models.BooleanField(default=False)),
                ("progress", models.FloatField(default=0)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("start_time", models.DateTimeField(blank=True, null=True)),
                ("end_time", models.DateTimeField(blank=True, null=True)),
                ("required_resources", models.JSONField(default=dict)),
                (
                    "assigned_to",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("attempts", models.IntegerField(default=0)),
                ("results", models.JSONField(blank=True, default=dict, null=True)),
                (
                    "error_details",
                    models.JSONField(blank=True, default=dict, null=True),
                ),
                (
                    "docker_image",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "parent_task",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subtasks",
                        to="tasks.task",
                    ),
                ),
                (
                    "workflow",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="workflows.workflow",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tâche",
                "verbose_name_plural": "Tâches",
                "ordering": ["-is_subtask", "created_at"],
            },
        ),
    ]
