# Generated by Django 4.1.13 on 2025-04-25 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="input_files",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="task",
            name="output_files",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="task",
            name="volunteer_preference",
            field=models.CharField(
                choices=[
                    ("ANY", "Tous types"),
                    ("CPU_INTENSIVE", "Calcul intensif CPU"),
                    ("GPU_REQUIRED", "GPU nécessaire"),
                    ("NETWORK_INTENSIVE", "Transfert intensif réseau"),
                    ("LOW_RESOURCE", "Ressources limitées"),
                    ("HIGH_MEMORY", "Mémoire importante"),
                ],
                default="ANY",
                max_length=20,
            ),
        ),
    ]
