# Generated by Django 5.2 on 2025-05-05 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0002_task_input_files_task_output_files_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="matrix_block_col_end",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="task",
            name="matrix_block_col_start",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="task",
            name="matrix_block_row_end",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="task",
            name="matrix_block_row_start",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="task",
            name="matrix_data",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
